--------------------------------------------------------
--  File created - Saturday-April-01-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence REPORT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CLEMENT"."REPORT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 2001 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence WEATHER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CLEMENT"."WEATHER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1001 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table HTE_REPORT
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "CLEMENT"."HTE_REPORT" 
   (	"REPORT_ID" NUMBER(10,0), 
	"DATE_REPORT" TIMESTAMP (6), 
	"LATITUDE" FLOAT(53), 
	"LONGITUDE" FLOAT(53), 
	"TEMPERATURE" FLOAT(53), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"WEATHER_ID" NUMBER(10,0), 
	"RN_" NUMBER(10,0)
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table HTE_WEATHER
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "CLEMENT"."HTE_WEATHER" 
   (	"WEATHER_ID" NUMBER(10,0), 
	"WEATHER" VARCHAR2(255 CHAR), 
	"RN_" NUMBER(10,0)
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

  CREATE TABLE "CLEMENT"."REPORT" 
   (	"REPORT_ID" NUMBER(10,0), 
	"DATE_REPORT" TIMESTAMP (6), 
	"LATITUDE" FLOAT(53), 
	"LONGITUDE" FLOAT(53), 
	"TEMPERATURE" FLOAT(53), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"WEATHER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WEATHER
--------------------------------------------------------

  CREATE TABLE "CLEMENT"."WEATHER" 
   (	"WEATHER_ID" NUMBER(10,0), 
	"WEATHER" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CLEMENT.HTE_REPORT
SET DEFINE OFF;
REM INSERTING into CLEMENT.HTE_WEATHER
SET DEFINE OFF;
REM INSERTING into CLEMENT.REPORT
SET DEFINE OFF;
Insert into CLEMENT.REPORT (REPORT_ID,DATE_REPORT,LATITUDE,LONGITUDE,TEMPERATURE,USERNAME,WEATHER_ID) values ('1102',to_timestamp('31/03/23 23:29:21,000000000','DD/MM/RR HH24:MI:SSXFF'),'45,7884','3,112','17,8','Nero','3');
Insert into CLEMENT.REPORT (REPORT_ID,DATE_REPORT,LATITUDE,LONGITUDE,TEMPERATURE,USERNAME,WEATHER_ID) values ('1103',to_timestamp('31/03/23 23:29:21,000000000','DD/MM/RR HH24:MI:SSXFF'),'45,7792','3,0897','15,3','Bob','1');
Insert into CLEMENT.REPORT (REPORT_ID,DATE_REPORT,LATITUDE,LONGITUDE,TEMPERATURE,USERNAME,WEATHER_ID) values ('1104',to_timestamp('31/03/23 23:29:21,000000000','DD/MM/RR HH24:MI:SSXFF'),'45,6069','2,9808','14,6','Charlie','2');
Insert into CLEMENT.REPORT (REPORT_ID,DATE_REPORT,LATITUDE,LONGITUDE,TEMPERATURE,USERNAME,WEATHER_ID) values ('1105',to_timestamp('31/03/23 23:29:21,000000000','DD/MM/RR HH24:MI:SSXFF'),'45,6592','3,255','18,2','David','4');
REM INSERTING into CLEMENT.WEATHER
SET DEFINE OFF;
Insert into CLEMENT.WEATHER (WEATHER_ID,WEATHER) values ('1','Ciel bleu');
Insert into CLEMENT.WEATHER (WEATHER_ID,WEATHER) values ('2','Quelques nuages');
Insert into CLEMENT.WEATHER (WEATHER_ID,WEATHER) values ('3','Eclaircies');
Insert into CLEMENT.WEATHER (WEATHER_ID,WEATHER) values ('4','Couvert');
Insert into CLEMENT.WEATHER (WEATHER_ID,WEATHER) values ('5','Brouillard');
Insert into CLEMENT.WEATHER (WEATHER_ID,WEATHER) values ('6','Averses');
Insert into CLEMENT.WEATHER (WEATHER_ID,WEATHER) values ('7','Pluie');
Insert into CLEMENT.WEATHER (WEATHER_ID,WEATHER) values ('8','Neige');
--------------------------------------------------------
--  DDL for Trigger REPORT_TIMESTAMP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CLEMENT"."REPORT_TIMESTAMP" 
BEFORE INSERT OR UPDATE ON CLEMENT.REPORT 
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :NEW.date_report := SYSDATE;
END;
/
ALTER TRIGGER "CLEMENT"."REPORT_TIMESTAMP" ENABLE;
--------------------------------------------------------
--  Constraints for Table HTE_WEATHER
--------------------------------------------------------

  ALTER TABLE "CLEMENT"."HTE_WEATHER" MODIFY ("RN_" NOT NULL ENABLE);
  ALTER TABLE "CLEMENT"."HTE_WEATHER" ADD PRIMARY KEY ("RN_") ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "CLEMENT"."REPORT" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLEMENT"."REPORT" MODIFY ("LATITUDE" NOT NULL ENABLE);
  ALTER TABLE "CLEMENT"."REPORT" MODIFY ("LONGITUDE" NOT NULL ENABLE);
  ALTER TABLE "CLEMENT"."REPORT" MODIFY ("TEMPERATURE" NOT NULL ENABLE);
  ALTER TABLE "CLEMENT"."REPORT" ADD PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HTE_REPORT
--------------------------------------------------------

  ALTER TABLE "CLEMENT"."HTE_REPORT" MODIFY ("RN_" NOT NULL ENABLE);
  ALTER TABLE "CLEMENT"."HTE_REPORT" ADD PRIMARY KEY ("RN_") ENABLE;
--------------------------------------------------------
--  Constraints for Table WEATHER
--------------------------------------------------------

  ALTER TABLE "CLEMENT"."WEATHER" MODIFY ("WEATHER_ID" NOT NULL ENABLE);
  ALTER TABLE "CLEMENT"."WEATHER" ADD PRIMARY KEY ("WEATHER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "CLEMENT"."REPORT" ADD CONSTRAINT "FKIB8MRBYMLNTQWA5AXE0H96DLW" FOREIGN KEY ("WEATHER_ID")
	  REFERENCES "CLEMENT"."WEATHER" ("WEATHER_ID") ENABLE;
